@firstUserId = 00000000-0000-0000-0000-000000000001
@secondUserId = 00000000-0000-0000-0000-000000000002
@thirdUserId = 00000000-0000-0000-0000-000000000003
@fourthUserId = 00000000-0000-0000-0000-000000000004
@locationId = 00000000-0000-0000-0000-000000000001
@fistBookingDate = 2021-03-20T15:00:00
@secondBookingDate = 2021-03-20T15:00:00
@rescheduleDate = 2021-03-20T18:00:00

@contentType = application/json

###

# @name createBooking
POST https://localhost:5001/bookings
Content-Type: {{contentType}}

{
  "StartDate": "{{fistBookingDate}}",
  "LocationId": "{{locationId}}",
  "UserIds": [
    "{{firstUserId}}",
    "{{secondUserId}}"
  ]
}

###

@bookingId = {{createBooking.response.body.$.id}}

GET https://localhost:5001/bookings/{{bookingId}}
Content-Type: {{contentType}}

###


POST https://localhost:5001/bookings
Content-Type: {{contentType}}

{
  "StartDate": "{{secondBookingDate}}",
  "LocationId": "{{locationId}}",
  "UserIds": [
    "{{thirdUserId}}",
    "{{fourthUserId}}"
  ]
}

###

DELETE  https://localhost:5001/bookings/{{bookingId}}
Content-Type: {{contentType}}

###

GET  https://localhost:5001/bookings
Content-Type: {{contentType}}

###

@bookingId = {{createBooking.response.body.$.id}}

PUT https://localhost:5001/bookings/{{bookingId}}/reschedule
Content-Type: {{contentType}}

{
  "StartDate": "{{rescheduleDate}}",
  "LocationId": "{{locationId}}",
  "UserIds": [
    "{{firstUserId}}",
    "{{secondUserId}}"
  ]
}

###